import Head from "next/head";
import Layout from "../src/layout/Layout";
import { API_URLS } from "../src/util/API_URL";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Banner from "../src/atoms/Banner";
import { Container } from "@mui/material";

const About = ({ data }) => {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>Tasty Food | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Layout>
        <div className="about">
          {/* <Banner title={"Foods"} subTitle={"Details"} /> */}
          <Container fixed className="container">
            hi
          </Container>
        </div>
      </Layout>
    </>
  );
};

export default About;

export async function getServerSideProps({ locale }) {
  const res = await fetch(API_URLS.HOME, API_URLS.HEADER_GET);
  const data = await res.json();
  return {
    props: {
      data,
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}
