import Head from "next/head";
import HomeLayout from "../src/layout/HomeLayout";
import Link from "next/link";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { API_URLS } from "../src/util/API_URL";

const Home = ({ data }) => {
  const { t } = useTranslation();
  console.log(data.data);

  return (
    <>
      <Head>
        <title>Tasty Food | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <HomeLayout>
        <main className="home">
          <h1>{t("React")} </h1>

          <Link href="/profile"> Profile</Link>
        </main>
      </HomeLayout>
    </>
  );
};
export default Home;

export async function getServerSideProps({ locale }) {
  const res = await fetch(API_URLS.HOME, API_URLS.HEADER_GET);
  const data = await res.json();
  return {
    props: {
      data,
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}
