import { ChangeTheme } from "@/src/context/ThemeContext";
import Head from "next/head";

export default function Home() {
  const { theme } = ChangeTheme();
  return (
    <>
      <Head>
        <title>Tasty Food | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className={`home ${theme}`}>hi</main>
    </>
  );
}
