import Head from "next/head";
import HomeLayout from "../src/layout/HomeLayout";
import Link from "next/link";
import { useTranslation } from "react-i18next";
import i18n from "@/src/i18n";

export default function Home() {
  const { t, i18n } = useTranslation();

  return (
    <>
      <Head>
        <title>Tasty Food | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <HomeLayout>
        <main className="home">
          <h1>{t("React")} </h1>
          <h2>{t("Home")}</h2>
          <h3>{t("Contact")}</h3>
          <h3>{t("About")}</h3> <Link href="/profile"> Profile</Link>
        </main>
      </HomeLayout>
    </>
  );
}
