import Head from "next/head";
import Layout from "../src/layout/Layout";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Link from "next/link";

const Profile = () => {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>Tasty Food | Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Layout>
        <div className="profile">
          profile
          <h1>{t("React")} </h1>
          <h2>{t("Home")}</h2>
          <h3>{t("Contact")}</h3>
          <Link href={"./"}>Home</Link>
        </div>
      </Layout>
    </>
  );
};

export default Profile;

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}
