import Head from "next/head";
import Layout from "../src/layout/Layout";

const register = () => {
  return (
    <>
      <Head>
        <title>Tasty Food | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Layout>
        <div className="register">register</div>
      </Layout>
    </>
  );
};

export default register;
